openapi: 3.0.0
servers:
  - url: 'http://eocdb.io/api/v01'
info:
  title: eocdb-server
  version: "0.1.0-dev.2"
  description: |
    RESTful API for the EUMETSAT Ocean Colour In-Situ Database.
    How we utilise HTTP methods:
    * GET: get existing items - read only.
    * PUT: add new items.
    * POST: update existing items.
    * DELETE: delete existing items.
  contact:
    email: eocdb@eumetsat.eu
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: Service
    description: Access to service info.
  - name: Store
    description: Access to the store.
  - name: Datasets
    description: Access to measurement datasets.
  - name: DocFiles
    description: Access to documentation files.
  - name: Users
    description: Access to users.
paths:
  '/service/info':
    get:
      tags:
        - Service
      summary: Get service information
      description: Returns information about the service as a dictionary of key-value pairs.
      operationId: getServiceInfo
      security:
        - api_key: []
  '/store/info':
    get:
      tags:
        - Store
      summary: Get store information
      description: Returns information about the store as a dictionary of key-value pairs.
      operationId: getStoreInfo
      security:
        - api_key: []
  '/store/upload':
    post:
      tags:
        - Store
      summary: Batch mode upload of files
      description: Upload datasets and documentation files and insert them into the store.
      operationId: uploadStoreFiles
      security:
        - eocdb_auth:
            - 'write:datasets'
            - 'read:datasets'
  '/store/download':
    get:
      tags:
        - Store
      summary: Batch mode download of files
      description: Download a ZIP file of datasets and optionally documentaion files for the given query from the store.
      operationId: downloadStoreFiles
  # TODO by forman: address publishing/hiding datasets
  # '/datasets/publish/{id}':
  '/datasets/validate':
    post:
      tags:
        - Datasets
      summary: Validate a dataset
      description: Validates the given dataset and returns a validation report.
      operationId: validateDataset
  '/datasets':
    get:
      tags:
        - Datasets
      summary: Find datasets
      description: Querys datasets by search expression, bounding box, time range, etc.
      operationId: findDatasets
      security:
        - api_key: []
    put:
      tags:
        - Datasets
      summary: Add a new dataset
      description: Adds a new dataset to the store and returns a dataset reference.
      operationId: addDataset
      security:
        - eocdb_auth:
            - 'write:datasets'
            - 'read:datasets'
    post:
      tags:
        - Datasets
      summary: Update an existing dataset
      description: Updates an existing dataset to the store.
      operationId: updateDataset
      security:
        - eocdb_auth:
            - 'write:datasets'
            - 'read:datasets'
  '/datasets/{id}':
    get:
      tags:
        - Datasets
      summary: Get dataset by ID
      description: Returns a single dataset by ID.
      operationId: getDatasetById
      security:
        - api_key: []
    delete:
      tags:
        - Datasets
      summary: Delete a dataset
      description: Deletes an existing dataset by ID.
      operationId: deleteDataset
      security:
        - eocdb_auth:
            - 'write:datasets'
            - 'read:datasets'
  '/datasets/{affil}/{project}/{cruise}':
    get:
      tags:
        - Datasets
      summary: Get all datasets for path
      description: Returns all dataset references for given path=affil/project/cruise.
      operationId: getDatasetsInPath
      security:
        - eocdb_auth:
            - 'read:datasets'
  '/datasets/{affil}/{project}/{cruise}/{name}':
    get:
      tags:
        - Datasets
      summary: Get dataset file from path
      description: Gets a dataset file for given path=affil/project/cruise.
      operationId: getDatasetByName
      security:
        - eocdb_auth:
            - 'write:datasets'
            - 'read:datasets'
  '/datasets/{id}/qcinfo':
    get:
      tags:
        - Datasets
      summary: Get dataset QC information
      description: Gets a dataset's quality control information.
      operationId: getDatasetQcInfo
      security:
        - eocdb_auth:
            - 'write:datasets'
            - 'read:datasets'
    post:
      tags:
        - Datasets
      summary: Set dataset QC information
      description: Sets a dataset's quality control information.
      operationId: setDatasetQcInfo
      security:
        - eocdb_auth:
            - 'write:datasets'
            - 'read:datasets'
  '/docfiles':
    put:
      tags:
        - DocFiles
      summary: Add documentation file
      description: Adds a new documentation file for given path=affil/project/cruise.
      operationId: addDocFile
      security:
        - eocdb_auth:
            - 'write:datasets'
            - 'read:datasets'
    post:
      tags:
        - DocFiles
      summary: Update documentation file
      description: Updates an existing documentation file for given path=affil/project/cruise.
      operationId: updateDocFile
      security:
        - eocdb_auth:
            - 'write:datasets'
            - 'read:datasets'
  '/docfiles/{affil}/{project}/{cruise}':
    get:
      tags:
        - DocFiles
      summary: Get documentation files for path
      description: Get documentation file references for given path=affil/project/cruise.
      operationId: getDocFilesInPath
  '/docfiles/{affil}/{project}/{cruise}/{name}':
    get:
      tags:
        - DocFiles
      summary: Get documentation file for path
      description: Gets binary documentation file for given path=affil/project/cruise.
      operationId: getDocFileByName
    delete:
      tags:
        - DocFiles
      summary: Delete documentation file from path
      description: Deletes a documentation file for given path=affil/project/cruise.
      operationId: deleteDocFile
      security:
        - eocdb_auth:
            - 'write:docFiles'
            - 'read:docFiles'
  '/users':
    post:
      tags:
        - Users
      summary: Add user
      description: Registers a new user. This can only be done by the logged in user.
      operationId: createUser
  '/users/login':
    get:
      tags:
        - Users
      summary: Login user
      description: Logs a user into the system using given credentials.
      operationId: loginUser
  '/users/logout':
    get:
      tags:
        - Users
      summary: Logout user
      description: Logs out current logged-in user.
      operationId: logoutUser
  '/users/{id}':
    get:
      tags:
        - Users
      summary: Get user information
      description: Gets user information by user ID.
      operationId: getUserByID
    put:
      tags:
        - Users
      summary: Update user information
      description: Uopdates user information by user ID. This can only be done by the logged in user.
      operationId: updateUser
    delete:
      tags:
        - Users
      summary: Remove user
      description: Removes the user with the given user ID. This can only be done by the logged in user.
      operationId: deleteUser
components:
  securitySchemes:
    eocdb_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://eocdb.io/oauth/dialog'
          scopes:
            'write:datasets': modify datasets in your account
            'read:datasets': read your datasets
            'write:docFiles': modify documentation files in your account
            'read:docFiles': read your documentation files
            'write:users': modify users
            'read:users': read users
    api_key:
      type: apiKey
      name: api_key
      in: header
