name: ocdb-server2

channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.6
  #
  # production dependencies
  #
  - numpy =1.14.3
  - pymongo =3.7.1
  - pyyaml =3.12
  - tornado =5.0.2
  - chardet
  - pip:
    - ftptool
  #
  # development dependencies
  #
  - pip:
    - mongomock==3.12.0
  - pytest =3.5.1
  - pytest-cov =2.5.1
  - flake8 =3.5.0
