name: ocdb-server

channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.6
  #
  # production dependencies
  #
  - numpy
  - pymongo
  - pyyaml
  - tornado
  - chardet
  - pip
  - pip:
    - ftptool
    #
    # development dependencies
    #
    - mongomock
  #
  # development dependencies
  #
  - pytest
  - pytest-cov
  - flake8
