store_path: ~/.ocdb/store

admin_user:
  name: chef
  id: eocdb_administrator
  password: eocdb_chef
  roles: [admin, submit]

databases:
  default:
    type: ocdb.db.mongo_db_driver.MongoDbDriver
    primary: true
    parameters:
        url: "mongodb://ocdb-db:27017/ocdb"


mode: dev