store_path: ~/.ocdb/store

admin_user:
  name: chef
  id: eocdb_administrator
  password: eocdb_chef
  roles: [admin, submit]

databases:
  default:
    type: eocdb.db.mongo_db_driver.MongoDbDriver
    primary: true
    parameters:
        url: "mongodb://localhost:27017/eocdb"


mode: dev